# Dockerfile para desarrollo de sipe.backend (Node.js + Express)
FROM node:22-alpine

WORKDIR /usr/src/app

COPY package.json package-lock.json ./
RUN npm install

# Instalar nodemon globalmente
RUN npm install -g nodemon

COPY . .

EXPOSE 4000

CMD ["nodemon", "app/server.js"]
